FROM node:20-alpine AS development

WORKDIR /app

RUN npm install -g pnpm

COPY package.json pnpm-lock.yaml ./
RUN pnpm install

COPY prisma ./prisma
COPY . .

RUN pnpm run prisma:generate

EXPOSE 3000

CMD ["pnpm", "run", "dev"]
